### ISSUE TITLE
Node KUBEADM_JOIN_FLAGS being set to env var KUBEADM_INIT_FLAGS

### ISSUE THREAD

**Issue by jbw976** [galexrt/k8s-vagrant-multi-node#10]
On this line of the Vagrantfile for the nodes, we see `KUBEADM_JOIN_FLAGS` getting set to the environment variable of `KUBEADM_INIT_FLAGS`:
https://github.com/galexrt/k8s-vagrant-multi-node/blob/master/Vagrantfile_nodes#L16

Is that intentional or a mistake?

**Comment by galexrt** [comment]
Oh yes, that is correct. That must be `KUBEADM_JOIN_FLAGS` in the`Vagrantfile_nodes` all the way.
