### ISSUE TITLE
VMs should use a 4.x kernel

### ISSUE THREAD

**Issue by jbw976** [galexrt/k8s-vagrant-multi-node#16]
The kernels for the VMs are 3.10:
```
[vagrant@node2 ~]$ uname -a
Linux node2 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
A more recent kernel would be nice to have, especially for Rook/Ceph issues like the following:
https://rook.io/docs/rook/master/common-issues.html#rook-agent-modprobe-exec-format-error

**Comment by galexrt** [comment]
I'll probably look into using Fedora instead CentOS then, because having to install an up-to-date kernel on CentOS and also rebooting before the nodes would be useable would be "too much" time.
