### ISSUE TITLE
Nothing happens while running with defaults

### ISSUE THREAD

**Issue by saedabdu** [galexrt/k8s-vagrant-multi-node#22]
Hello there, 
Thanks for sharing this.

Running with the defaults using `make up -j 3` doesn't produce anything.
I have downgraded my vagrant to `2.1.1` 
Appreciate any feedback

**Comment by galexrt** [comment]
@saedabdu What do you mean with `doesn't produce anything.`? No output at all?

Run `make up -j3 > make-up.log` and post the `make-up.log` file here.

**Comment by saedabdu** [comment]
@galexrt Yes no output at all.
make-up.log is empty

**Comment by galexrt** [comment]
@saedabdu And you are full filling all requirements from here https://github.com/galexrt/k8s-vagrant-multi-node#prerequisites ?
Your `make` is working (e.g., does it work with other Makefiles)?

I have just run `make up -j3` on my Linux machine and I get output.

**Comment by saedabdu** [comment]
@galexrt Yes all requirements are satisfied. Make is definitly working on my Linux.

`$ make --version
GNU Make 4.2.1`

VirtualBox
Version 5.2.22 r126257

`$ rsync --version
rsync  version 3.1.3  protocol version 31`

**Comment by saedabdu** [comment]
Update: 
I just tried this on a different Linux box, output is different this time. Will update you shortly.

**Comment by galexrt** [comment]
@jbw976 Could you please try to run `make up -j3` on your Mac just to see if it works on another machine too

**Comment by saedabdu** [comment]
Alright, i had a problem with make in my dotfiles, and fixed it.
Now i get this when i try to run `make up -j3`
`make[1]: Entering directory '/home/saed/k8s-vagrant-multi-node'
make[2]: Entering directory '/home/saed/k8s-vagrant-multi-node'
vagrant up
VAGRANT_VAGRANTFILE=Vagrantfile_nodes NODE=1 vagrant up
VAGRANT_VAGRANTFILE=Vagrantfile_nodes NODE=2 vagrant up
Bringing machine 'node2' up with 'virtualbox' provider...
Bringing machine 'node1' up with 'virtualbox' provider...
Bringing machine 'master' up with 'virtualbox' provider...
==> node2: Box 'generic/fedora27' could not be found. Attempting to find and install...
    node2: Box Provider: virtualbox
    node2: Box Version: >= 0
==> node1: Box 'generic/fedora27' could not be found. Attempting to find and install...
    node1: Box Provider: virtualbox
    node1: Box Version: >= 0
==> master: Box 'generic/fedora27' could not be found. Attempting to find and install...
    master: Box Provider: virtualbox
    master: Box Version: >= 0
==> node1: Loading metadata for box 'generic/fedora27'
    node1: URL: https://vagrantcloud.com/generic/fedora27
==> master: Loading metadata for box 'generic/fedora27'
    master: URL: https://vagrantcloud.com/generic/fedora27
==> node2: Loading metadata for box 'generic/fedora27'
    node2: URL: https://vagrantcloud.com/generic/fedora27
The metadata for the box was malformed. The exact error
is shown below. Please contact the maintainer of the box so
that this issue can be fixed.

765: unexpected token at ''
make[2]: *** [Makefile:110: start-master] Error 1
make[2]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
	33: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	32: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/machine.rb:194:in `action'
	31: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/machine.rb:194:in `call'
	30: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/environment.rb:598:in `lock'
	29: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/machine.rb:208:in `block in action'
	28: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/machine.rb:239:in `action_raw'
	27: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `run'
	26: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/util/busy.rb:19:in `busy'
	25: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `block in run'
	24: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/builder.rb:116:in `call'
	23: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
	22: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	21: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
	20: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	19: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `run'
	18: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/util/busy.rb:19:in `busy'
	17: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `block in run'
	16: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/builder.rb:116:in `call'
	15: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
	14: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	13: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
	12: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/builtin/handle_box.rb:36:in `call'
	11: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/builtin/handle_box.rb:36:in `synchronize'
	10: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/builtin/handle_box.rb:42:in `block in call'
	 9: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/builtin/handle_box.rb:82:in `handle_box'
	 8: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `run'
	 7: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/util/busy.rb:19:in `busy'
	 6: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `block in run'
	 5: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/builder.rb:116:in `call'
	 4: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
	 3: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/builtin/box_add.rb:118:in `call'
	 2: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/builtin/box_add.rb:198:in `add_from_metadata'
	 1: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/builtin/box_add.rb:198:in `open'
/opt/vagrant/embedded/gems/gems/vagrant-2.1.1/lib/vagrant/action/builtin/box_add.rb:198:in `initialize': No such file or directory @ rb_sysopen - /home/saed/.vagrant.d/tmp/box77d86e31b7bbc990694eeaff3e55c71bccdcbfaf (Errno::ENOENT)
`

**Comment by saedabdu** [comment]
@galexrt 
I think this is related to the BOX_IMAGE.
I tried to override it with `BOX_IMAGE ?= centos/7` in the Makefile, same error occurs.

**Comment by saedabdu** [comment]
I got my Vagrant in a bad state. The fix was making sure I had no vagrant/Vbox  running.
All is good now. Thanks for support @galexrt  .. Closing.

**Comment by galexrt** [comment]
@saedabdu Thanks for following up!
