### ISSUE TITLE
Is kubectl a pre-requisite?

### ISSUE THREAD

**Issue by simon3270** [galexrt/k8s-vagrant-multi-node#24]
I ran "make up" on a fresh MacBook Pro (MacOS 10.14) and it failed when trying to use kubectl to set up the cluster (after the VMs were created):
    kubectl \
        config set-cluster \
        etc, etc
I ran "brew install kubernetes-cli" (could have used "port install kubectl" if I had been using Macports), and re-ran the "make up" and all was well.

**Comment by galexrt** [comment]
@simon3270 Yes, `kubectl` is a pre-requisite.

I have opened a PR to add it to the pre-requisite and also a variable to make it optional (see #25).

**Comment by simon3270** [comment]
Thanks for that. BTW, this repo is awesome!
