### ISSUE TITLE
Ubuntu - systemd-resolved breaks dns

### ISSUE THREAD

**Issue by DanyC97** [galexrt/k8s-vagrant-multi-node#33]
As documented [here](https://github.com/kubernetes/kubernetes/pull/63691) we should add for ubuntu `--resolv-conf=/run/systemd/resolve/resolv.conf` 

I've looked myself where would be the best place to add it and i think it could be [here](https://github.com/galexrt/k8s-vagrant-multi-node/blob/master/vagrantfiles/ubuntu/common) ?

**Comment by galexrt** [comment]
@DanyC97 If you look at the `/var/lib/kubelet/kubeadm-flags.env` file, it is automatically set by kubeadm, see https://github.com/kubernetes/kubernetes/pull/64665.

**Comment by DanyC97** [comment]
i didn't see it in first place, i'll take a look again. thank you @galexrt
