### ISSUE TITLE
coredns doesn't start - failed to find plugin "loopback" in path [/opt/cni/bin]

### ISSUE THREAD

**Issue by y0zg** [galexrt/k8s-vagrant-multi-node#39]
Hi, please check how to fix this properly

`make start -j 3`

OS Fedora

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

```
get pods -n kube-system
NAME                             READY   STATUS              RESTARTS   AGE
coredns-86c58d9df4-w79cc         0/1     ContainerCreating   0          12m
coredns-86c58d9df4-w9q65         0/1     ContainerCreating   0          12m
etcd-master                      1/1     Running             3          12m
kube-apiserver-master            1/1     Running             3          12m
kube-controller-manager-master   1/1     Running             3          12m
kube-proxy-qkvx5                 1/1     Running             1          12m
kube-proxy-v66zb                 1/1     Running             1          12m
kube-proxy-z9trz                 1/1     Running             1          12m
kube-scheduler-master            1/1     Running             3          12m

```

```
k get events -n kube-system
LAST SEEN   TYPE      REASON                   KIND         MESSAGE
56m         Normal    SandboxChanged           Pod          Pod sandbox changed, it will be killed and re-created.
22m         Normal    Scheduled                Pod          Successfully assigned kube-system/coredns-86c58d9df4-7vqkw to node1
22m         Warning   FailedCreatePodSandBox   Pod          Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "7d9c818779632409b7a9d82f474c58411ca4b67cc65b571fc3a4d852add23e09" network for pod "coredns-86c58d9df4-7vqkw": NetworkPlugin cni failed to set up pod "coredns-86c58d9df4-7vqkw_kube-system" network: failed to find plugin "loopback" in path [/opt/cni/bin], failed to clean up sandbox container "7d9c818779632409b7a9d82f474c58411ca4b67cc65b571fc3a4d852add23e09" network for pod "coredns-86c58d9df4-7vqkw": NetworkPlugin cni failed to teardown pod "coredns-86c58d9df4-7vqkw_kube-system" network: failed to find plugin "flannel" in path [/opt/cni/bin]]

```

**Comment by sp98** [comment]
Facing this same issue.  Followed below steps to make it working for now. Waiting for an actual fix. 

1. Download cni plugin from https://github.com/containernetworking/plugins/releases
    I used 'cni-plugins-amd64-v0.7.5.tgz'

2.  Create opt/cni/bin directory in each node.

3.  Make the ‘vagrant’ user own this directory. 
   sudo chown vagrant /opt/cni/bin

4. Copy downloaded file (in step 1) to each Node. 
- scp cni-plugins-amd64-v0.7.5.tgz  vagrant@<ip-of-the-node>:/opt/cni/bin/
 (Get IP address of the each node using ifconfig)

5. Extract the cni plugin in each node.
    tar -xzvf  cni-plugins-amd64-v0.7.5.tgz

**Comment by dklesev** [comment]
When using Fedora it seems to be related to the cni binary path. The correct path seems to be `/usr/libexec/cni` (according to packaging guidelines of RH/CentOS/Fedora?).

So a workaround (tested only with default settings - fedora as os) is to replace some lines for **KUBELET_EXTRA_ARGS**

([here](https://github.com/galexrt/k8s-vagrant-multi-node/blob/master/vagrantfiles/Vagrantfile_common#L132) and [here](https://github.com/galexrt/k8s-vagrant-multi-node/blob/master/vagrantfiles/Vagrantfile_common#L178))
`sed -i 's|KUBELET_EXTRA_ARGS=|KUBELET_EXTRA_ARGS=--node-ip=#{NODE_IP} --cni-bin-dir=/usr/libexec/cni|' "$KUBELET_EXTRA_ARGS_FILE"` 

I got coredns running, but not tested yet if there are any other issues.
