### ISSUE TITLE
Problem with wrong IP on the master/worker

### ISSUE THREAD

**Issue by YiannisGkoufas** [galexrt/k8s-vagrant-multi-node#42]
I have run into the issue described here https://medium.com/@joatmon08/playing-with-kubeadm-in-vagrant-machines-part-2-bac431095706
Basically the master,workers where getting 10.x addresses instead of 192.x and I was unable to get the logs of the pods, exec in them etc

**Comment by galexrt** [comment]
Closing as this should not occur if you are on the latest version.

Please create a new issue should the issue reoccur, with the full `make up` output attached.
