### ISSUE TITLE
Temporary failure resolving 'us.archive.ubuntu.com'

### ISSUE THREAD

**Issue by YiannisGkoufas** [galexrt/k8s-vagrant-multi-node#44]
**Is this a bug report or feature request?**
* Bug Report

**Bug Report**

**Expected behavior:**
K8s master and node starting up with ubuntu image
**Deviation from expected behavior:**
```
Fetched 3,685 kB in 2min 15s (27.3 kB/s)
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-common_2.30-21ubuntu1~18.04_amd64.deb  Temporary failure resolving 'us.archive.ubuntu.com'
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/b/binutils/libbinutils_2.30-21ubuntu1~18.04_amd64.deb  Temporary failure resolving 'us.archive.ubuntu.com'
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-x86-64-linux-gnu_2.30-21ubuntu1~18.04_amd64.deb  Temporary failure resolving 'us.archive.ubuntu.com'
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils_2.30-21ubuntu1~18.04_amd64.deb  Temporary failure resolving 'us.archive.ubuntu.com'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> master: Checking for guest additions in VM...
```
**How to reproduce it (minimal and precise):**
If I specify ubuntu as box I get the errors above. There could be something wrong with my system as well, but I could really use some help to pinpoint the exact issue.

**Environment**:
* OS of the machine (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
* Kernel of the machine (e.g. `uname -a`):
4.15.0-47-generic
* `make versions` output:
```
=== BEGIN Version Info ===
Repo state: 6f84df85b9339bedfa327a18b5cfdffb6a99566d (dirty? NO)
make: /usr/bin/make
kubectl: /usr/bin/kubectl
grep: /bin/grep
cut: /usr/bin/cut
rsync: /usr/bin/rsync
openssl: /usr/bin/openssl
/dev/urandom: OK
Vagrant version:
Vagrant 2.2.4
vboxmanage version:
6.0.6r130049
=== END Version Info ===
```

**Comment by galexrt** [comment]
Well that's the Ubuntu Box image for you.
Only Ubuntu users have reported DNS resolution failures, even though the DNS servers are "overwritten" to `8.8.8.8` (see https://github.com/galexrt/k8s-vagrant-multi-node/blob/e65032e881877d39dbd652561f6ec061fc5f2241/vagrantfiles/ubuntu/pre#L3-L5).

Closing as there isn't really anything that can be done about that, besides for using, e.g., the Fedora or CentOS image(s).
