### ISSUE TITLE
Deleting kubectl config on clean

### ISSUE THREAD

**Issue by woohhan** [galexrt/k8s-vagrant-multi-node#54]
**Is this a bug report or feature request?**
* Feature Request

**Are there any similar features already existing:**

**What should the feature do:**
I'm using on my e2e test, but everytime I created a cluster and delete it, kubectl config still remains. It will be great If the config is deleted.

**What would be solved through this feature:**

**Does this have an impact on existing features:**

**Comment by galexrt** [comment]
@woohhan If you are talking about `make clean` (or `make clean-master`) command, I have opened #55 to implement this.

I will merge it in the next few hours.
