### ISSUE TITLE
`make up` hangs sometimes

### ISSUE THREAD

**Issue by galexrt** [galexrt/k8s-vagrant-multi-node#62]
**Bug Report**

**Expected behavior:**

`make up` not to hang.

**Deviation from expected behavior:**

Running `make up` seems to hang sometimes on my test system (make version: `GNU make 4.3`). `remake` works fine..

**How to reproduce it (minimal and precise):**

Run, e.g., `make up -j6`

**Environment**:
* OS of the machine (e.g. from `/etc/os-release`): Manjaro Linux
* Kernel of the machine (e.g. `uname -a`): 5.5.11
* `make versions` output:
```
=== BEGIN Version Info ===
Repo state: bb8e2652802b823748f49b276f270202f31649ca (dirty? NO)
make: /usr/bin/make
kubectl: /usr/bin/kubectl
grep: /usr/bin/grep
cut: /usr/bin/cut
rsync: /usr/bin/rsync
openssl: /usr/bin/openssl
/dev/urandom: OK
Vagrant version:
Vagrant 2.2.7
=== END Version Info ===
```

***

@woohhan have you experienced `make up` hanging in your environment(s)? I'm trying to make sure it is just my machine having this issue right now.

**Comment by woohhan** [comment]
@galexrt In my e2e test, it works fine. The version information is as follows.

- OS of the machine: Ubuntu 18.04.3 LTS
- Kernel of the machine: 4.15.0
- Vagrant Version: 2.2.6
- Repo: Master

I had a problem with Vagrant not working when system memory was low. Since Vagrant does not show a perfect log, it would be good to check the Vagrant.

**Comment by galexrt** [comment]
@woohhan Thanks for responding!

Mhh this really seems to be caused by my machine being weird. Closing my issue then.

**Comment by masaeedu** [comment]
@galexrt `make up` seems to hang every so often for me. The CPU is pegged at 100% by the relevant qemu-system process.

**Comment by masaeedu** [comment]
Always gets stuck at this point:

![image](https://user-images.githubusercontent.com/3674056/89728868-e344ce00-da1f-11ea-9edf-bab3cc04f353.png)

**Comment by galexrt** [comment]
@masaeedu Can you provide the whole `make up` log when the hang occurs with all variables set.
