### ISSUE TITLE
Duplicate IP conflict

### ISSUE THREAD

**Issue by sophalHong** [galexrt/k8s-vagrant-multi-node#78]
If MASTER_IP is set to 192.168.26.11, then master and node-1 will have the same IP address.  
https://github.com/galexrt/k8s-vagrant-multi-node/blob/e194569005454c61adc190e78eb70fd2cad47ba8/vagrantfiles/Vagrantfile_vars#L26

suggestion:
NODE_IP = NODE_IP_NW + (NODE + MASTER_IP.split(".").last.to_i).to_s

**Comment by galexrt** [comment]
Thanks for creating the issue and posting the sugestion!

I have pushed your suggestion as the fix, thanks!
