### ISSUE TITLE
Ubuntu vagrant file error since vagrant cloud dependency

### ISSUE THREAD

**Issue by anencore94** [galexrt/k8s-vagrant-multi-node#93]
**Bug Report**

make up with `BOX_OS=ubuntu` make error since it gets vagrant image from `https://app.vagrantup.com/generic/boxes/ubuntu1804/versions/3.2.10/providers/virtualbox.box`, But this page is not accessible now.

**Expected behavior:**

I know it's not the fault of this repo, but the vagrant cloud page in HashiCorp. But if this issue happend, how about get image from older version in that page ? such as v3.2.8 for ubuntu 1804 image

**Deviation from expected behavior:**

**How to reproduce it (minimal and precise):**

BOX_OS=ubuntu KUBERNETES_VERSION=v1.17.3 make up -j2

**Environment**:
* OS of the machine (e.g. from `/etc/os-release`):
* Kernel of the machine (e.g. `uname -a`):
* `make versions` output: 
```plain
OUTPUT_HERE
```

**Comment by galexrt** [comment]
The image is not pinned by k8s-vagrant-multi-node to such a specific version, so it seems that the `vagrant box update` or `vagrant box add` command on your host tries to pull a non-existing version (at least I can't see on the boxes list).

On a brand new machine, it is downloading `v3.2.8`:

```
=== END Version Info ===
make[2]: Leaving directory '/home/atrost/Projects/github.com/galexrt/k8s-vagrant-multi-node'
==> box: Loading metadata for box 'generic/ubuntu1804'
    box: URL: https://vagrantcloud.com/generic/ubuntu1804
==> box: Adding box 'generic/ubuntu1804' (v3.2.8) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/generic/boxes/ubuntu1804/versions/3.2.8/providers/virtualbox.box
Download redirected to host: vagrantcloud-files-production.s3-accelerate.amazonaws.com
    box: Calculating and comparing box checksum...
==> box: Successfully added box 'generic/ubuntu1804' (v3.2.8) for 'virtualbox'!
make start-master
make[2]: Entering directory '/home/atrost/Projects/github.com/galexrt/k8s-vagrant-multi-node'
```

***

Please post your whole logs, thanks!

**Comment by anencore94** [comment]
There was tag v3.2.10 and link to v3.2.10 page (with wrong link) in https://app.vagrantup.com/generic/boxes/ubuntu1804, just a few hours ago.
But now it disappears.. so the problem fixed naturally.

I definitely saw the v3.2.10 release page was there, you can check with this [page](https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=updated&provider=&q=generic%2Fubuntu1804). 3.2.10 was released 4 days ago..

Anyway, now v3.2.10 gone, I could boot ubuntu vm with v3.2.8 well. Thanks though! @galexrt

**Comment by galexrt** [comment]
Mhh weird, maybe there is an issue with that box version. Closing the issue.
